import { z } from "zod";
import { chatArtifactSchema } from "./chat-response";

type JsonSchema = {
  type?: string | string[];
  const?: unknown;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  additionalProperties?: unknown;
  oneOf?: JsonSchema[];
};

function emitType(schema: JsonSchema, indent: number): string {
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (schema.oneOf) {
    return schema.oneOf.map((option) => emitType(option, indent)).join(" | ");
  }

  const type = schema.type;
  if (type === "string") return "string";
  if (type === "number" || type === "integer") return "number";
  if (type === "boolean") return "boolean";
  if (type === "array") {
    return `Array<${schema.items ? emitType(schema.items, indent) : "unknown"}>`;
  }
  if (type === "object") {
    if (!schema.properties) {
      const extra = schema.additionalProperties;
      if (extra && typeof extra === "object") {
        return `Record<string, ${emitType(extra as JsonSchema, indent)}>`;
      }
      return "Record<string, unknown>";
    }
    const required = new Set(schema.required ?? []);
    const pad = "  ".repeat(indent);
    const inner = "  ".repeat(indent + 1);
    const fields = Object.entries(schema.properties).map(([key, value]) => {
      const optional = required.has(key) ? "" : "?";
      const safeKey = /^[A-Za-z_][A-Za-z0-9_]*$/.test(key)
        ? key
        : JSON.stringify(key);
      let fieldType = emitType(value, indent + 1);
      const extra = value.additionalProperties;
      if (
        extra &&
        typeof extra === "object" &&
        Object.keys(extra).length === 0 &&
        value.properties?.type
      ) {
        fieldType = `{ type: string; [key: string]: unknown }`;
      }
      return `${inner}${safeKey}${optional}: ${fieldType};`;
    });
    return `{\n${fields.join("\n")}\n${pad}}`;
  }
  return "unknown";
}

function variantName(schema: JsonSchema): string {
  const tag = schema.properties?.type?.const;
  if (typeof tag !== "string") return "ChatArtifact";
  return `${tag.replace(/(^|_)([a-z])/g, (_, _sep: string, ch: string) => ch.toUpperCase())}Data`;
}

export function frontendChatResponseModule(): string {
  const json = z.toJSONSchema(chatArtifactSchema) as JsonSchema;
  const variants = json.oneOf ?? [];
  const aliases = variants.map((schema) => {
    const name = variantName(schema);
    return `export type ${name} = ${emitType(schema, 0)};`;
  });
  const union = variants.map(variantName).join(" | ");

  return `// Generated by bun run check:surfaces. Do not edit.

export type ChatResponseType = "text" | "code" | "api_spec" | "sql" | "diagram";

${aliases.join("\n\n")}

export type ChatArtifact = ${union};
export type ChatResponseData = ChatArtifact;

export type ChatApiResponse =
  | { ok: false; error: string }
  | { ok: true; type: ChatResponseType; data: ChatResponseData };
`;
}
