// Generated by bun run check:surfaces. Do not edit.

export type ChatResponseType = "text" | "code" | "api_spec" | "sql" | "diagram";

export type TextData = {
  type: "text";
  text: string;
};

export type CodeData = {
  type: "code";
  language: string;
  filename: string;
  title: string;
  description: string;
  code: string;
};

export type ApiSpecData = {
  type: "api_spec";
  method: string;
  endpoint: string;
  description: string;
  auth: string;
  parameters: Array<{
    name: string;
    in: string;
    required: boolean;
    description: string;
    schema: { type: string; [key: string]: unknown };
  }>;
  responses: Record<string, {
    description: string;
    schema: Record<string, unknown>;
    example: unknown;
  }>;
  componentSchemas: Record<string, unknown>;
  notes?: Array<string>;
};

export type SqlData = {
  type: "sql";
  dialect: string;
  sql: string;
  reasoning: string;
};

export type DiagramData = {
  type: "diagram";
  diagramType: string;
  title: string;
  content: string;
};

export type ChatArtifact = TextData | CodeData | ApiSpecData | SqlData | DiagramData;
export type ChatResponseData = ChatArtifact;

export type ChatApiResponse =
  | { ok: false; error: string }
  | { ok: true; type: ChatResponseType; data: ChatResponseData };
